---
# Setup tasks.
    - include_tasks: "setup-{{ ansible_os_family }}.yml"

    - name: Add user node_exporter
      user:
        name: node_exporter
        shell: /bin/false
        system: true
        create_home: no

    - name: Ensure temporal directory exist
      file: state=directory path=/tmp/node-exporter/

    - name: Check latest Node Exporter version
      uri:
        url: https://api.github.com/repos/prometheus/node_exporter/releases/latest
        return_content: true
      register: node_exporter_latest

    - name: "Installing node exporter {{ node_exporter_latest.json.tag_name }}"
      loop: "{{ node_exporter_latest.json.assets }}"
      when: "'linux-amd64' in item.name"
      unarchive:
        remote_src: yes
        src: "{{ item.browser_download_url }}"
        dest: /tmp/node-exporter/
        keep_newer: yes
        extra_opts: [--strip-components=1]

    - name: Install Node Exporter
      ansible.builtin.copy:
        remote_src: yes
        src: /tmp/node-exporter/node_exporter
        dest: /usr/local/bin/node_exporter
        mode: '0731'

    - name: Create service node_exporter.service
      blockinfile:
        path: /etc/systemd/system/node_exporter.service
        block: |
          [Unit]
          Description=Prometheus Node Exporter
          Wants=network-online.target
          After=network-online.target
          [Service]
          User=node_exporter
          Group=node_exporter
          Type=simple
          ExecStart=/usr/local/bin/node_exporter
          [Install]
          WantedBy=multi-user.target
        create: true

    - name: systemctl daemon_reload
      systemd:
        daemon_reload: yes

    - name: Start and Enable node_exporter
      service:
        name: node_exporter
        state: started
        enabled: yes

    - name: Check whether port 9100 is available
      wait_for:
        port: 9100
        state: started
        timeout: 5