    - name: Node exporter - Red Hat like - Allow Node Exporter port
      ansible.posix.firewalld:
         port: 9100/tcp
         permanent: yes
         state: enabled
         immediate: yes
      when: ansible_facts['distribution'] != 'Amazon'

    - name: Amazon Linux - Enable EPEL Repository on Amazon Linux 2
      shell: amazon-linux-extras install epel -y
      become: True
      when: ansible_facts['distribution'] == 'Amazon' and ansible_facts['distribution_major_version'] == '2'