    - name: Debian - Install packages
      apt:
        name:
          - apt-transport-https
          - software-properties-common
          - wget
        state: latest

    - name: Debian - Allow Node Exporter port
      community.general.ufw:
        rule: allow
        port: '9100'
      when:  ufw_enable|bool == true

    - name: Debian - update package repositories and get latest package information
      apt:
        update_cache: yes