---
   - name: Restart prometheus
     ansible.builtin.service:
       name: prometheus
       state: restarted

   - name: Red Hat like - Restart Firewalld
     service:
       name: firewalld
       state: restarted
     when: ansible_facts['distribution'] != 'Amazon'