    - name: Red Hat like - Create Grafana repo
      ansible.builtin.template:
        src: files/grafana.repo.j2
        dest: /etc/yum.repos.d/grafana.repo

    - name: Red Hat like - Allow Grafana port
      ansible.posix.firewalld:
        port: 3000/tcp
        permanent: yes
        state: enabled
      when: ansible_facts['distribution'] != 'Amazon'

   # Need a Reboot for take effect
    - name: Red Hat like -  Put SELinux in permissive mode, logging actions that would be blocked.
      ansible.posix.selinux:
        policy: targeted
        state: permissive
      when: ansible_facts['distribution'] != 'Amazon'