    - name: Red Hat like - Install tools for HashiCorp repo
      yum:
        name:
           - yum-utils
        state: present

    - name: Red Hat like - Add HashiCorp yum repo
      command: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
      args:
        creates: /etc/yum.repos.d/hashicorp.repo
      when: ansible_facts['distribution'] != 'Amazon'

    - name: Amazon Linux - Add HashiCorp yum repo
      command: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      args:
        creates: /etc/yum.repos.d/hashicorp.repo
      when: ansible_facts['distribution'] == 'Amazon'