---
# Setup tasks.

    - name: Define the backend configuration at init
      community.general.terraform:
        project_path: "{{ terraform_base_dir }}/{{ terraform_name }}"
        state: "present"
        force_init: true
        backend_config:
          region: "{{ backend_region }}"
          bucket: "{{ backend_bucket }}"
          key: "{{ backend_key }}"
          dynamodb_table: "{{ backend_dynamodb_table }}"
          encrypt: "true"
        variables:
          region: "{{ deploy_region }}"
          role_arn: "{{ deploy_role_arn }}"
      register: init

    - name: "Display output: Init Terraform"
      debug:
        msg: "{{ init.stdout }}"