---
# Setup tasks.

    - include_tasks: "setup-{{ ansible_os_family }}.yml"

    - name: Install MySQL
      package:
        name:
          - mysql-server
        state: latest

    - name: Red Hat like - Start and Enable MySQL
      service:
        name: mysqld
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Debian like - Start and Enable MySQL
      service:
        name: mysql
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == 'Debian'

    - name: Ansible replace string example
      replace:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '127.0.0.1'
        replace: '0.0.0.0' # only for non prod environments
      when: ansible_facts['os_family'] == 'Debian'

    - name: MySQL - Check whether port 3306 is available
      wait_for:
        port: 3306
        state: started
        timeout: 5