---
# Setup tasks.

    - name: Portainer - Ensure directory exists
      file:
        state: directory
        path: /home/{{ ansible_user }}/docker/portainer
      become_user: "{{ ansible_user }}"

    - name: Portainer - Disable UFW
      community.general.ufw:
        state: disabled

    - name: Portainer - Template a file to /etc/file.conf
      ansible.builtin.template:
        src: files/docker-compose.yml.j2
        dest: /home/{{ ansible_user }}/docker/portainer/docker-compose.yml
      become_user: "{{ ansible_user }}"

    - name: Portainer - Start Portainer container
      community.docker.docker_compose:
        project_src: /home/{{ ansible_user }}/docker/portainer/
        files:
          - docker-compose.yml
      become_user: "{{ ansible_user }}"