    - name: Debian - Add the Grafana GPG key.
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        state: present

    - name: Debian - Add the official Jenkins Linux repository.
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/jenkins.list
        line: deb https://pkg.jenkins.io/debian-stable binary/
        create: yes

    - name: Debian - update package repositories and get latest package information
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Debian - Allow Jenkins port
      community.general.ufw:
        rule: allow
        port: '8080'

    - name: Debian - Install JDK
      apt: name=openjdk-11-jdk state=present