    - name: Debian - update package repositories and get latest package information
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Ubuntu - Install necessary tools for Docker
      package:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - lsb-release
        state: latest

    - name: Ubuntu - Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Ubuntu - Add Docker’s official GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      changed_when: false

    - name: Ubuntu - Add the official Docker Linux repository.
      shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      changed_when: false

    - name: Ubuntu - update package repositories and get latest package information
      apt:
        update_cache: yes