    - name: Debian - update package repositories and get latest package information
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Debian - Install NFS tools
      apt: name=nfs-common state=latest

    - name: Debian - Install Python 3 and another tools
      apt: name=python3,python3-pip state=present

    - name: Debian - Ensure apt is set up to work with https sources
      apt: name=apt-transport-https state=latest

    - name: Debian - update package repositories and get latest package information
      apt:
        update_cache: yes
        cache_valid_time: 3600